/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package Testing.petstore.models.operations;

import Testing.petstore.utils.SpeakeasyMetadata;
import com.fasterxml.jackson.annotation.JsonProperty;

public class DeletePetRequest {
    @SpeakeasyMetadata("header:style=simple,explode=false,name=api_key")
    public String apiKey;

    public DeletePetRequest withApiKey(String apiKey) {
        this.apiKey = apiKey;
        return this;
    }
    
    /**
     * Pet id to delete
     */
    @SpeakeasyMetadata("pathParam:style=simple,explode=false,name=petId")
    public Long petId;

    public DeletePetRequest withPetId(Long petId) {
        this.petId = petId;
        return this;
    }
    
    public DeletePetRequest(@JsonProperty("petId") Long petId) {
        this.petId = petId;
  }
}
