/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package Testing.petstore.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;
import java.net.http.HttpResponse;

public class FindPetsByTagsResponse {
    
    public byte[] body;

    public FindPetsByTagsResponse withBody(byte[] body) {
        this.body = body;
        return this;
    }
    
    
    public String contentType;

    public FindPetsByTagsResponse withContentType(String contentType) {
        this.contentType = contentType;
        return this;
    }
    
    /**
     * successful operation
     */
    
    public Testing.petstore.models.shared.Pet[] pets;

    public FindPetsByTagsResponse withPets(Testing.petstore.models.shared.Pet[] pets) {
        this.pets = pets;
        return this;
    }
    
    
    public Integer statusCode;

    public FindPetsByTagsResponse withStatusCode(Integer statusCode) {
        this.statusCode = statusCode;
        return this;
    }
    
    
    public HttpResponse<byte[]> rawResponse;

    public FindPetsByTagsResponse withRawResponse(HttpResponse<byte[]> rawResponse) {
        this.rawResponse = rawResponse;
        return this;
    }
    
    public FindPetsByTagsResponse(@JsonProperty("ContentType") String contentType, @JsonProperty("StatusCode") Integer statusCode) {
        this.contentType = contentType;
        this.statusCode = statusCode;
  }
}
