/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package Testing.petstore.models.operations;

import Testing.petstore.utils.SpeakeasyMetadata;

public class FindPetsByStatusRequest {
    /**
     * Status values that need to be considered for filter
     */
    @SpeakeasyMetadata("queryParam:style=form,explode=true,name=status")
    public FindPetsByStatusStatus status;

    public FindPetsByStatusRequest withStatus(FindPetsByStatusStatus status) {
        this.status = status;
        return this;
    }
    
    public FindPetsByStatusRequest(){}
}
