/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package Testing.petstore.models.operations;

import Testing.petstore.utils.SpeakeasyMetadata;

public class FindPetsByTagsRequest {
    /**
     * Tags to filter by
     */
    @SpeakeasyMetadata("queryParam:style=form,explode=true,name=tags")
    public String[] tags;

    public FindPetsByTagsRequest withTags(String[] tags) {
        this.tags = tags;
        return this;
    }
    
    public FindPetsByTagsRequest(){}
}
