/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package Testing.petstore.models.operations;

import com.fasterxml.jackson.annotation.JsonValue;

/**
 * FindPetsByStatusStatus - Status values that need to be considered for filter
 */
public enum FindPetsByStatusStatus {
    AVAILABLE("available"),
    PENDING("pending"),
    SOLD("sold");

    @JsonValue
    public final String value;

    private FindPetsByStatusStatus(String value) {
        this.value = value;
    }
}
