/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package Testing.petstore.models.operations;

import Testing.petstore.utils.SpeakeasyMetadata;
import com.fasterxml.jackson.annotation.JsonProperty;

public class GetInventorySecurity {
    @SpeakeasyMetadata("security:scheme=true,type=apiKey,subtype=header,name=api_key")
    public String apiKey;

    public GetInventorySecurity withApiKey(String apiKey) {
        this.apiKey = apiKey;
        return this;
    }
    
    public GetInventorySecurity(@JsonProperty("api_key") String apiKey) {
        this.apiKey = apiKey;
  }
}
