/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package Testing.petstore.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;
import java.net.http.HttpResponse;

public class GetInventoryResponse {
    
    public String contentType;

    public GetInventoryResponse withContentType(String contentType) {
        this.contentType = contentType;
        return this;
    }
    
    
    public Integer statusCode;

    public GetInventoryResponse withStatusCode(Integer statusCode) {
        this.statusCode = statusCode;
        return this;
    }
    
    
    public HttpResponse<byte[]> rawResponse;

    public GetInventoryResponse withRawResponse(HttpResponse<byte[]> rawResponse) {
        this.rawResponse = rawResponse;
        return this;
    }
    
    /**
     * successful operation
     */
    
    public java.util.Map<String, Integer> getInventory200ApplicationJSONObject;

    public GetInventoryResponse withGetInventory200ApplicationJSONObject(java.util.Map<String, Integer> getInventory200ApplicationJSONObject) {
        this.getInventory200ApplicationJSONObject = getInventory200ApplicationJSONObject;
        return this;
    }
    
    public GetInventoryResponse(@JsonProperty("ContentType") String contentType, @JsonProperty("StatusCode") Integer statusCode) {
        this.contentType = contentType;
        this.statusCode = statusCode;
  }
}
