/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package Testing.petstore.models.operations;

import Testing.petstore.utils.SpeakeasyMetadata;

public class GetPetByIdSecurity {
    @SpeakeasyMetadata("security:scheme=true,type=apiKey,subtype=header,name=api_key")
    public String apiKey;

    public GetPetByIdSecurity withApiKey(String apiKey) {
        this.apiKey = apiKey;
        return this;
    }
    
    @SpeakeasyMetadata("security:scheme=true,type=oauth2,name=Authorization")
    public String petstoreAuth;

    public GetPetByIdSecurity withPetstoreAuth(String petstoreAuth) {
        this.petstoreAuth = petstoreAuth;
        return this;
    }
    
    public GetPetByIdSecurity(){}
}
