/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package Testing.petstore.models.operations;

import Testing.petstore.utils.SpeakeasyMetadata;
import com.fasterxml.jackson.annotation.JsonProperty;

public class GetUserByNameRequest {
    /**
     * The name that needs to be fetched. Use user1 for testing. 
     */
    @SpeakeasyMetadata("pathParam:style=simple,explode=false,name=username")
    public String username;

    public GetUserByNameRequest withUsername(String username) {
        this.username = username;
        return this;
    }
    
    public GetUserByNameRequest(@JsonProperty("username") String username) {
        this.username = username;
  }
}
