/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package Testing.petstore.models.operations;

import Testing.petstore.utils.SpeakeasyMetadata;

public class LoginUserRequest {
    /**
     * The password for login in clear text
     */
    @SpeakeasyMetadata("queryParam:style=form,explode=true,name=password")
    public String password;

    public LoginUserRequest withPassword(String password) {
        this.password = password;
        return this;
    }
    
    /**
     * The user name for login
     */
    @SpeakeasyMetadata("queryParam:style=form,explode=true,name=username")
    public String username;

    public LoginUserRequest withUsername(String username) {
        this.username = username;
        return this;
    }
    
    public LoginUserRequest(){}
}
