/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package Testing.petstore.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;
import java.net.http.HttpResponse;

public class LoginUserResponse {
    
    public String contentType;

    public LoginUserResponse withContentType(String contentType) {
        this.contentType = contentType;
        return this;
    }
    
    
    public java.util.Map<String, String[]> headers;

    public LoginUserResponse withHeaders(java.util.Map<String, String[]> headers) {
        this.headers = headers;
        return this;
    }
    
    
    public Integer statusCode;

    public LoginUserResponse withStatusCode(Integer statusCode) {
        this.statusCode = statusCode;
        return this;
    }
    
    
    public HttpResponse<byte[]> rawResponse;

    public LoginUserResponse withRawResponse(HttpResponse<byte[]> rawResponse) {
        this.rawResponse = rawResponse;
        return this;
    }
    
    /**
     * successful operation
     */
    
    public String loginUser200ApplicationJSONString;

    public LoginUserResponse withLoginUser200ApplicationJSONString(String loginUser200ApplicationJSONString) {
        this.loginUser200ApplicationJSONString = loginUser200ApplicationJSONString;
        return this;
    }
    
    /**
     * successful operation
     */
    
    public String loginUser200ApplicationXMLString;

    public LoginUserResponse withLoginUser200ApplicationXMLString(String loginUser200ApplicationXMLString) {
        this.loginUser200ApplicationXMLString = loginUser200ApplicationXMLString;
        return this;
    }
    
    public LoginUserResponse(@JsonProperty("ContentType") String contentType, @JsonProperty("StatusCode") Integer statusCode) {
        this.contentType = contentType;
        this.statusCode = statusCode;
  }
}
