/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package Testing.petstore.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;
import java.net.http.HttpResponse;

public class PlaceOrderRawResponse {
    
    public String contentType;

    public PlaceOrderRawResponse withContentType(String contentType) {
        this.contentType = contentType;
        return this;
    }
    
    /**
     * successful operation
     */
    
    public Testing.petstore.models.shared.Order order;

    public PlaceOrderRawResponse withOrder(Testing.petstore.models.shared.Order order) {
        this.order = order;
        return this;
    }
    
    
    public Integer statusCode;

    public PlaceOrderRawResponse withStatusCode(Integer statusCode) {
        this.statusCode = statusCode;
        return this;
    }
    
    
    public HttpResponse<byte[]> rawResponse;

    public PlaceOrderRawResponse withRawResponse(HttpResponse<byte[]> rawResponse) {
        this.rawResponse = rawResponse;
        return this;
    }
    
    public PlaceOrderRawResponse(@JsonProperty("ContentType") String contentType, @JsonProperty("StatusCode") Integer statusCode) {
        this.contentType = contentType;
        this.statusCode = statusCode;
  }
}
