/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package Testing.petstore.models.operations;

import Testing.petstore.utils.SpeakeasyMetadata;
import com.fasterxml.jackson.annotation.JsonProperty;

public class UpdateUserJsonRequest {
    /**
     * Update an existent user in the store
     */
    @SpeakeasyMetadata("request:mediaType=application/json")
    public Testing.petstore.models.shared.User user;

    public UpdateUserJsonRequest withUser(Testing.petstore.models.shared.User user) {
        this.user = user;
        return this;
    }
    
    /**
     * name that need to be deleted
     */
    @SpeakeasyMetadata("pathParam:style=simple,explode=false,name=username")
    public String username;

    public UpdateUserJsonRequest withUsername(String username) {
        this.username = username;
        return this;
    }
    
    public UpdateUserJsonRequest(@JsonProperty("username") String username) {
        this.username = username;
  }
}
