/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package Testing.petstore.models.operations;

import Testing.petstore.utils.SpeakeasyMetadata;
import com.fasterxml.jackson.annotation.JsonProperty;

public class UpdateUserFormRequest {
    /**
     * Update an existent user in the store
     */
    @SpeakeasyMetadata("request:mediaType=application/x-www-form-urlencoded")
    public Testing.petstore.models.shared.User user;

    public UpdateUserFormRequest withUser(Testing.petstore.models.shared.User user) {
        this.user = user;
        return this;
    }
    
    /**
     * name that need to be deleted
     */
    @SpeakeasyMetadata("pathParam:style=simple,explode=false,name=username")
    public String username;

    public UpdateUserFormRequest withUsername(String username) {
        this.username = username;
        return this;
    }
    
    public UpdateUserFormRequest(@JsonProperty("username") String username) {
        this.username = username;
  }
}
