/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package Testing.petstore.models.operations;

import Testing.petstore.utils.SpeakeasyMetadata;
import com.fasterxml.jackson.annotation.JsonProperty;

public class UpdatePetWithFormRequest {
    /**
     * Name of pet that needs to be updated
     */
    @SpeakeasyMetadata("queryParam:style=form,explode=true,name=name")
    public String name;

    public UpdatePetWithFormRequest withName(String name) {
        this.name = name;
        return this;
    }
    
    /**
     * ID of pet that needs to be updated
     */
    @SpeakeasyMetadata("pathParam:style=simple,explode=false,name=petId")
    public Long petId;

    public UpdatePetWithFormRequest withPetId(Long petId) {
        this.petId = petId;
        return this;
    }
    
    /**
     * Status of pet that needs to be updated
     */
    @SpeakeasyMetadata("queryParam:style=form,explode=true,name=status")
    public String status;

    public UpdatePetWithFormRequest withStatus(String status) {
        this.status = status;
        return this;
    }
    
    public UpdatePetWithFormRequest(@JsonProperty("petId") Long petId) {
        this.petId = petId;
  }
}
