/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package Testing.petstore.models.operations;

import Testing.petstore.utils.SpeakeasyMetadata;
import com.fasterxml.jackson.annotation.JsonProperty;

public class UpdateUserRawRequest {
    /**
     * Update an existent user in the store
     */
    @SpeakeasyMetadata("request:mediaType=application/xml")
    public byte[] requestBody;

    public UpdateUserRawRequest withRequestBody(byte[] requestBody) {
        this.requestBody = requestBody;
        return this;
    }
    
    /**
     * name that need to be deleted
     */
    @SpeakeasyMetadata("pathParam:style=simple,explode=false,name=username")
    public String username;

    public UpdateUserRawRequest withUsername(String username) {
        this.username = username;
        return this;
    }
    
    public UpdateUserRawRequest(@JsonProperty("username") String username) {
        this.username = username;
  }
}
