/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package Testing.petstore.models.shared;

import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * ApiResponse - successful operation
 */
public class ApiResponse {
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("code")
    public Integer code;

    public ApiResponse withCode(Integer code) {
        this.code = code;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("message")
    public String message;

    public ApiResponse withMessage(String message) {
        this.message = message;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("type")
    public String type;

    public ApiResponse withType(String type) {
        this.type = type;
        return this;
    }
    
    public ApiResponse(){}
}
