/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package Testing.petstore.models.shared;

import com.fasterxml.jackson.annotation.JsonValue;

/**
 * OrderStatus - Order Status
 */
public enum OrderStatus {
    PLACED("placed"),
    APPROVED("approved"),
    DELIVERED("delivered");

    @JsonValue
    public final String value;

    private OrderStatus(String value) {
        this.value = value;
    }
}
