/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package Testing.petstore.models.shared;

import Testing.petstore.utils.DateTimeDeserializer;
import Testing.petstore.utils.DateTimeSerializer;
import Testing.petstore.utils.SpeakeasyMetadata;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import java.time.OffsetDateTime;

public class Order {
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("complete")
    @SpeakeasyMetadata("form:name=complete")
    public Boolean complete;

    public Order withComplete(Boolean complete) {
        this.complete = complete;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("id")
    @SpeakeasyMetadata("form:name=id")
    public Long id;

    public Order withId(Long id) {
        this.id = id;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("petId")
    @SpeakeasyMetadata("form:name=petId")
    public Long petId;

    public Order withPetId(Long petId) {
        this.petId = petId;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("quantity")
    @SpeakeasyMetadata("form:name=quantity")
    public Integer quantity;

    public Order withQuantity(Integer quantity) {
        this.quantity = quantity;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonSerialize(using = DateTimeSerializer.class)
    @JsonDeserialize(using = DateTimeDeserializer.class)
    @JsonProperty("shipDate")
    @SpeakeasyMetadata("form:name=shipDate")
    public OffsetDateTime shipDate;

    public Order withShipDate(OffsetDateTime shipDate) {
        this.shipDate = shipDate;
        return this;
    }
    
    /**
     * Order Status
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("status")
    @SpeakeasyMetadata("form:name=status")
    public OrderStatus status;

    public Order withStatus(OrderStatus status) {
        this.status = status;
        return this;
    }
    
    public Order(){}
}
