/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package Testing.petstore.models.shared;

import Testing.petstore.utils.SpeakeasyMetadata;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * Pet - Create a new pet in the store
 */
public class Pet {
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("category")
    @SpeakeasyMetadata("form:name=category,json")
    public Category category;

    public Pet withCategory(Category category) {
        this.category = category;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("id")
    @SpeakeasyMetadata("form:name=id")
    public Long id;

    public Pet withId(Long id) {
        this.id = id;
        return this;
    }
    
    @JsonProperty("name")
    @SpeakeasyMetadata("form:name=name")
    public String name;

    public Pet withName(String name) {
        this.name = name;
        return this;
    }
    
    @JsonProperty("photoUrls")
    @SpeakeasyMetadata("form:name=photoUrls")
    public String[] photoUrls;

    public Pet withPhotoUrls(String[] photoUrls) {
        this.photoUrls = photoUrls;
        return this;
    }
    
    /**
     * pet status in the store
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("status")
    @SpeakeasyMetadata("form:name=status")
    public PetStatus status;

    public Pet withStatus(PetStatus status) {
        this.status = status;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("tags")
    @SpeakeasyMetadata("form:name=tags,json")
    public Tag[] tags;

    public Pet withTags(Tag[] tags) {
        this.tags = tags;
        return this;
    }
    
    public Pet(@JsonProperty("name") String name, @JsonProperty("photoUrls") String[] photoUrls) {
        this.name = name;
        this.photoUrls = photoUrls;
  }
}
