/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package Testing.petstore.models.shared;

import com.fasterxml.jackson.annotation.JsonValue;

/**
 * PetStatus - pet status in the store
 */
public enum PetStatus {
    AVAILABLE("available"),
    PENDING("pending"),
    SOLD("sold");

    @JsonValue
    public final String value;

    private PetStatus(String value) {
        this.value = value;
    }
}
