/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package Testing.petstore.models.shared;

import Testing.petstore.utils.SpeakeasyMetadata;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * User - Created user object
 */
public class User {
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("email")
    @SpeakeasyMetadata("form:name=email")
    public String email;

    public User withEmail(String email) {
        this.email = email;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("firstName")
    @SpeakeasyMetadata("form:name=firstName")
    public String firstName;

    public User withFirstName(String firstName) {
        this.firstName = firstName;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("id")
    @SpeakeasyMetadata("form:name=id")
    public Long id;

    public User withId(Long id) {
        this.id = id;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("lastName")
    @SpeakeasyMetadata("form:name=lastName")
    public String lastName;

    public User withLastName(String lastName) {
        this.lastName = lastName;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("password")
    @SpeakeasyMetadata("form:name=password")
    public String password;

    public User withPassword(String password) {
        this.password = password;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("phone")
    @SpeakeasyMetadata("form:name=phone")
    public String phone;

    public User withPhone(String phone) {
        this.phone = phone;
        return this;
    }
    
    /**
     * User Status
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("userStatus")
    @SpeakeasyMetadata("form:name=userStatus")
    public Integer userStatus;

    public User withUserStatus(Integer userStatus) {
        this.userStatus = userStatus;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("username")
    @SpeakeasyMetadata("form:name=username")
    public String username;

    public User withUsername(String username) {
        this.username = username;
        return this;
    }
    
    public User(){}
}
